Thought I'd try and migrate it to be an asyncio view and see how that behaves ... And the ridiculous red/blue colouring thing is a nightmare. So far, I've sprinkled async/await in various places and each results in an error (and the documentation for making an async CBV is ... thin) Currently, the error is this:
    streaming_content=await self.loop(
TypeError: object async_generator can't be used in 'await' expression

which is great, because there appear to be about 15 results in Google for that, more than half of which are either spam sites with the same content, or in languages I can't read, or unanswered/unexplained.

Sigh.